### ISSUE TITLE
viewport->size() does not appear to work as described in documentation

### ISSUE THREAD

**Issue by sdondley** [Corion/WWW-Mechanize-Chrome#6] opened 2018-06-19 01:06 UTC
On a Mac, High Sierra. Chrome Version 67.0.3396.87 (Official Build) (64-bit).

When viewport->size() is called without any arguments, a `Too few arguments for subroutine` error is thrown.

When called with arguments, (e.g. `viewport_size->({height => 768, width => 1024, deviceScaleFactor => 1})` a `mobile: boolean value expected` error is thrown. However, when a `mobile` argument is passed with a boolean value, the same error is still thrown.

**Comment by Corion** [comment] 2018-06-19 18:31
Thank you for reporting this bug. I can replicate it, and I think it is mainly caused by the module not passing in (all) the proper values. For ```mobile``` the true or false value must be ```JSON::PP::true``` (or ::false) I think.

As a workaround, you can pass in all the values explicitly.

I hope that I get to releasing a fixed version next weekend.

**Comment by sdondley** [comment] 2018-06-19 23:34
Thanks for getting back. And let me know if I can do anything to contribute to the module. Thanks for sharing your work.

**Comment by Corion** [comment] 2018-06-21 20:08
This is now addressed by 01923b . I still have some other bugs I want to fix before the 0.16 release, but I presume that I will make a release on the upcoming weekend.

Thanks again for reporting the bug!

**Comment by sdondley** [comment] 2018-06-21 20:09
Cool. Glad to help.

**Closed by Corion** 2018-06-21 20:08 UTC
Labels: bug
